### ISSUE TITLE
关于组件uploader

### ISSUE THREAD

**Issue by guigui730** [KuangPF/mpvue-weui#10]
wx.chooseImage里面设置count：1 无效。。而且在predivImage时  没有删除这个图片的地方，weui里有这个。help

**Comment by KuangPF** [comment]
### wx.chooseImage
 `wx.chooseImage` 提供了`count`参数，表示一次性最多可以选多少张图片，我测试了一下，当设置为1的时候只能选择一张图片，当设置为2或者3的时候可以选择多张图片，但上传的时候只会上传最开始选择的2张或者3张（其他数字暂时没测试），你可以再试下，如果还是不行的话可否提供一下运行的环境和代码，这样方便排除问题一点。
### wx.predivImage
微信提供的`wx.predivImage` API 目的是能够进行图片预览，看了一下官方文档，然后并没有提供删除的参数，在 H5 版的 WeUI 中的确有删除图片的地方，但是也只是一个示例，并没有具体的删除功能，而小程序版的 WeUI中并没有删除这个功能。不过在下次版本迭代的时候会考虑把删除这个功能加上，可以先提供一个思路：
在全屏预览的时候应该是没有办法删除的（如果有，请老大告知），但可以在每个上传小图的右上角添加一个删除按钮，然后删除事件，当点击删除的时候获取该图片地址在图片地址数组中的索引值，然后将这个值去掉，就可以达到删除的目的。

**Comment by guigui730** [comment]
你的这个删除功能跟我当时自己做的想法差不多  ，点个赞

**Comment by yy007668** [comment]
`deleteImg(e) {
      // console.log(e.currentTarget.id)
      let newArr = []
      for(let value of this.files){
        if(value !== e.currentTarget.id){
            newArr.push(value)
        }
      }
      this.files = newArr
    },


<div class="delete-icon" @click="deleteImg" :id="item">
   <img src="../../../static/img/delete64.png">
</div>`

自己写了一个
