### ISSUE TITLE
怎么没有网络请求相关的实例

### ISSUE THREAD

**Issue by shaibaoj** [KuangPF/mpvue-weui#14]
怎么没有网络请求相关的实例

**Comment by KuangPF** [comment]
这可能主要考虑到是 UI 方面的组件，没有添加网络请求相关的实例，如果要进行网络请求的话，可以用微信原生的 `wx.request`，当然这里推荐使用[fly框架](https://github.com/wendux/fly)，同时支持浏览器、小程序、Node、Weex的基于Promise的跨平台http请求库。可以让您在多个端上尽可能大限度的实现代码复用。

不过会可以考虑在下个版本迭代的时候加入网络请求相关的实例。
