### ISSUE TITLE
页面通讯相关案例最好也提供下

### ISSUE THREAD

**Issue by shaibaoj** [KuangPF/mpvue-weui#15]
页面通讯相关案例最好也提供下

**Comment by KuangPF** [comment]
在 v1.0.4 版本中会添加，已写入版本迭代计划。

**Comment by KuangPF** [comment]
已增加页面通讯相关案例，vuex 实现 [页面通讯相关案例](http://kuangpf.com/mpvue-weui/#/vuex)
