### ISSUE TITLE
是否考虑用less加入theme？

### ISSUE THREAD

**Issue by kala888** [KuangPF/mpvue-weui#16]
换主题颜色

**Comment by KuangPF** [comment]
你好，有点不太明白这个需求意思，你的意思是整体换一个色调还是...?

**Comment by kala888** [comment]
@KuangPF 对的，例如可以定义一套颜色的变量
![image](https://user-images.githubusercontent.com/1215976/39341696-f11443d6-4a06-11e8-856a-0ded30d15ef1.png)

**Comment by KuangPF** [comment]
这个到没有考虑，因为 `weui` 本身的色调这些就是基于微信主色调。如果想换个色调也可以考虑一下基于 `mpvue` 的 [zanui](https://github.com/armyja/mpvue-zanui)
