### ISSUE TITLE
发布的时候，/static/images/图片没有上传到服务器，无法显示

### ISSUE THREAD

**Issue by gemgin** [KuangPF/mpvue-weui#17]
还有个问题，就是报Cannot read property 'call' of undefined;at App onError function TypeError: Cannot read property 'call  的问题

**Comment by KuangPF** [comment]
你好，首先抱歉，没有及时反馈你所提的 issues。我这边测试了下，如果没有 `npm run build` 的话也是不能显示页面这些，你可以按照以下步骤试下，看能不能解决问题（针对于生产环境，非开发环境）：
* `npm run build`
* 用微信开发者工具编译`npm run build`的代码，然后上传到服务器

**Comment by DengfengQiu** [comment]
我也遇到了这个问题，在微信工具中是可以看到本地图片的，但是使用预览功能在手机上看就看不到。
更新mpvue到1.0.10和重新build都试过，还是没有用

**Comment by KuangPF** [comment]
已修复，[修复 static 图片路径问题](https://github.com/KuangPF/mpvue-weui/commit/0ade9226fb5b648e05db5b00598011454a3dcd1e)
