### ISSUE TITLE
怎么在项目中引入这套UI，不能通过npm方式么

### ISSUE THREAD

**Issue by rigelzhang** [KuangPF/mpvue-weui#18]
emmmm，如标题

**Comment by KuangPF** [comment]
* 暂不支持 npm 方式，主要是一个基于 `mpvue`的一个 demo 吧，没有将其组件化[mpvue-weui 是什么](http://kuangpf.com/mpvue-weui/#/README)

* 不过目前将其常用的 `picker` 组件进行了封装，支持 `npm` 方式引入 [mpvue-picker](https://github.com/KuangPF/mpvue-picker)
