### ISSUE TITLE
请问作者有没有mpvue实现的星级评分的demo

### ISSUE THREAD

**Issue by pardonhan** [KuangPF/mpvue-weui#19]
就是类似订外卖完了评价的时候点星星的操作

**Comment by KuangPF** [comment]
下次迭代加上，[版本迭代需求描述](https://github.com/KuangPF/mpvue-weui/issues/11)

**Comment by KuangPF** [comment]
已添加  [星级评分](https://kuangpf.com/mpvue-weui/#/rate)
