### ISSUE TITLE
请问作者有没有mpvue实现的多区间的slider滑块组件

### ISSUE THREAD

**Issue by Addieo** [KuangPF/mpvue-weui#20]

**Comment by KuangPF** [comment]
额，其实有点不太明白具体的意思，能举个栗子不

**Comment by Addieo** [comment]
比如一个slider range滑块，有一个最大值和最小值，用户可以拖拽改变最大值，也可改变最小值，取一个区间值的value！

**Comment by KuangPF** [comment]
目前通过 `slider` 组件拖拽改变最大值或者最小值，，不知是不是你所描述的意思 [slider demo](http://kuangpf.com/mpvue-weui/#/slider)

**Comment by Addieo** [comment]
谢谢您的回答，我想描述的意思是这个slider上面有两个拖拽的按钮，一个调最小值，一个调最大值，类似于这个demo         https://www.vue-js.com/topic/5ad5974b4a2737ef0df431b9

**Comment by Uhouzz1994** [comment]
同问

**Comment by KuangPF** [comment]
看了微信官方的文档，没有找到同时有两个滑块的情况，然后开始打算用两个`slider`来实现这种效果，发现效果并不好。之后看了 @Addieo 提供的案例，可以用`$refs`进行一个 `slider` 组件的封装，但是如果涉及到 `$refs` 一般涉及到 `dom`操作，对于 `$refs`， `mpvue` 在 v1.0.9后可以通过 `$refs`获取子组件的引用，但普通节点暂不考虑支持 [mpvue issuess 73](https://github.com/Meituan-Dianping/mpvue/issues/73)，因此个人感觉有点不太容易实现。
如果有大佬能够实现的欢迎 `PR`
