### ISSUE TITLE
关于部分未封装组建的问题

### ISSUE THREAD

**Issue by huiyuye** [KuangPF/mpvue-weui#25]
![image](https://user-images.githubusercontent.com/13378079/41643233-39acb928-749d-11e8-9ff8-813f87d5ac02.png)
像这种跟原文件一样的，建议封装一下。很不规范，感觉很随意

**Comment by KuangPF** [comment]
谢谢指出不足，当时写可能只是想做成一个 demo 库，然后可能没考虑到这么多。对 mpvue-weui 的封装会考虑。
