### ISSUE TITLE
参考mpvue-weui方式引入weui-wxss，样式丢失的问题

### ISSUE THREAD

**Issue by zhongku** [KuangPF/mpvue-weui#26]
引入的weu.css是mpvue-weui项目的，结果很多样式丢失比如，颜色，圆角等。请教下是什么原因？

**Comment by KuangPF** [comment]
可以贴一下代码不，好方便排查问题。

**Comment by zhongku** [comment]
问题已经解决，非常感谢，我看了您的代码非常优雅，我们现在用您的框架来搭建一个项目，可能会有很大的失败可能。您这边有时间，帮我们处理些技术问题吗？我可以提供有偿服务的 项目地址https://github.com/zhongku/zkweb

**Comment by KuangPF** [comment]
哈哈～不敢当，有什么问题就直接提 issues 或者发邮件，1633397286@qq.com ,如果能帮您解决的肯定解决，是否有偿倒无所谓。

**Comment by zhongku** [comment]
可以加您QQ吗？还正想让您为我们的这个项目提供点指导，有偿解决肯定是合理的，我的QQ2839018，您加我也可以
