### ISSUE TITLE
运行 node build/dev-server.js 卡住不动

### ISSUE THREAD

**Issue by kenberkeley** [KuangPF/mpvue-weui#28]
可见：
https://github.com/Meituan-Dianping/mpvue/issues/518
https://github.com/Meituan-Dianping/mpvue/issues/522
https://github.com/Meituan-Dianping/mpvue/issues/562

测试环境：
Windows 10
node v9.10.1

**Comment by jcc** [comment]
+1

环境：
Mac 10.13.5
node v9.3.0
npm v6.1.0

**Comment by KuangPF** [comment]
我这边也遇见过了一次，将 /node_modules 删了然后重新安装就可以了
