### ISSUE TITLE
时间选择器为什么要把它写死成picker？我只想点击input的时候弹出下面的城市选择。。。

### ISSUE THREAD

**Issue by PythonNaChen** [KuangPF/mpvue-weui#29]
我想去掉这该死的边框怎么去除？boder:0 or boder:none 都没效果
<picker class="weui-btn" mode="region" :value="region" @change="CityChange">
                <div class="title"><span>*</span>省市区</div>
                <button type="default">选择城市</button>
            </picker>

**Comment by KuangPF** [comment]
不知道你说的边框是不是按钮的边框

![issues29](https://user-images.githubusercontent.com/20694238/43085280-2a6ab204-8ecd-11e8-96af-c9dafd77569e.png)
如果是的话，解决方法可以是这样：
``` vue
 <picker class="weui-btn" mode="region" :value="region" @change="CityChange">
      <span class="your-class">城市选择器</span>
 </picker>
```
然后样式这些自己写就可以了，不一定非要用  button
