### ISSUE TITLE
关于request

### ISSUE THREAD

**Issue by mystery66** [KuangPF/mpvue-weui#31]
npm install flyio 之后运行命令npm run dev 就报错，说相关依赖没找到，我也没有引入fly 到相应页面。
重装flyio 还是报一样的错

**Comment by KuangPF** [comment]
我将 flyio 更新到了 0.6.0，然后 npm run dev, 没有报错，你方便提供一下报错信息、node 版本以及运行环境不，这样排查起来容易点。

**Comment by mystery66** [comment]
解决了， node_modules 出了点问题，
