### ISSUE TITLE
关于预览安装

### ISSUE THREAD

**Issue by XiaodiKong** [KuangPF/mpvue-weui#32]
刚测试了下，把代码clone下来之后，npm 安装，运行，在dist文件夹中并未编译出app.js 等文件，请问是什么原因？

**Comment by MarcWong** [comment]
遇到同样的问题

**Comment by fisher7757** [comment]
你好，还是不能自动修改样式。 我clone以后，新增了一个页面，然后重新编译了一下、  打开页面以后，修改任何样式微信开发工具上面都不会变，只能停止编译然后再次npm run dev才可以编译出来

**Comment by KuangPF** [comment]
我测试了下，暂时没有复现你所说的问题。你在 main.json 里面是否添加了新增页面的路径。如果添加了，还是有问题，那把运行环境提供以及 mpvue 相关的版本号提供下。

**Comment by MarcWong** [comment]
@fisher7757 我觉得有可能是工作区太大，命令行没有监听到改动吧。
我自己的项目中迁移进去了一部分weui的组件，没有遇到你的情况。我建议你直接在自己的项目里加组件，而不是在这个weui库的基础上改。
