### ISSUE TITLE
定时器开启之后， 使用 clearInterval(this.timer)函数关闭不了定时器问题

### ISSUE THREAD

**Issue by lvjh** [KuangPF/mpvue-weui#34]
##  我使用如下代码在进入页面启动定时器，在离开页面关闭定时器功能，有什么问题吗？
> ###  我也尝试直接调用   clearInterval(this.timer);函数也关闭不了定时器，是不是调用的函数不对
> ### 代码如下：

```
mounted() {
    this.timer = setInterval(this.fetchCurrentDeviceData, 500)
    this.timer = setInterval(() => {
      this.fetchCurrentDeviceData();
    }, 1000)
  },

  beforeDestroy() {
    if (this.timer) { //如果定时器还在运行 或者直接关闭，不用判断
      clearInterval(this.timer); //关闭
    }
  },
```

**Comment by KuangPF** [comment]
你把 vue 的生命周期 beforeDestroy 改为小程序的 onHide 生命周期就可以了
``` vue
...
onHide() {
    clearInterval(this.timer);
},
...
```

**Comment by lvjh** [comment]
感谢您的回答！！
我现在有两个页面，一个是主页面，一个是设备页面
1，在设备页面，我使用您的方式 替代成如下代码，不能实现离开页面停止定时器功能。
2，在主页面，我使用onHide（）可以关掉， 但是再次进入页面定时器缺没有重新开启（使用mounted）。
...
mounted() {
    this.timer = setInterval(this.fetchCurrentDeviceData, 500)
    this.timer = setInterval(() => {
      this.fetchCurrentDeviceData();
    }, 1000)
  },

  onHide() {
    if (this.timer) { //如果定时器还在运行 或者直接关闭，不用判断
      clearInterval(this.timer); //关闭
    }
  },
...

**Comment by KuangPF** [comment]
可以参考 mpvue  [issues834](https://github.com/Meituan-Dianping/mpvue/issues/834)

**Comment by FxPixels** [comment]
如何onHide不可以，可以试试onUnLoad() 刚踩完这个坑
