### ISSUE TITLE
是不是不支持 onLaunch() 

### ISSUE THREAD

**Issue by zhainanfuli** [KuangPF/mpvue-weui#37]
App.vue  里的 created() , onLaunch() 其实没有执行了
加在 main.js 里也不执行

亲测 mpvue 本身是支持的，小弟不才，搞不定这个问题，Google 了一圈，没找到解决方案，麻烦大佬有时间看一下这个问题，万分感谢。

**Comment by KuangPF** [comment]
main.js 中 
``` javascript
const app = new Vue({
  App
})
```
改成

``` javascript
const app = new Vue(App)
```
