### ISSUE TITLE
navbar的tabClick没有对数据类型转换，导致激活状态的下划线没有变化，可以优化一下

### ISSUE THREAD

**Issue by wu529778790** [KuangPF/mpvue-weui#39]
tabClick (e) {
      this.activeIndex = Number(e.currentTarget.id)
    }
都转成数字类型就可以

**Comment by xieyihao** [comment]
:+1:   我也发现了 准备提个issues的

**Comment by KuangPF** [comment]
哈哈～谢谢指出，大佬们其实可以发个 `PR`  过来～

**Comment by flzyup** [comment]
目前最新版还是存在这个问题哦 @KuangPF 不准备修复下嘛

**Comment by KuangPF** [comment]
目前将 `mpvue` 更新至 2.0.5，貌似没有复现该问题 @flzyup 。
