### ISSUE TITLE
编译报错，按关掉的问题做的还是报错

### ISSUE THREAD

**Issue by qingjiaowochengzd** [KuangPF/mpvue-weui#4]
编译报错

Vue packages version mismatch:

- vue@1.0.1
- mpvue-template-compiler@1.0.3

**Comment by KuangPF** [comment]
可以方便提供一下代码和报错的信息不

**Comment by wxytongxue** [comment]
@KuangPF npm run dev 运行报上述错误

**Comment by KuangPF** [comment]
问题是由于一个包的版本问题，将`package.json`中的 `"mpvue-template-compiler": "^1.0.1"` 改成`"mpvue-template-compiler": "1.0.1"`，就装成 1.0.1的版本，目前先这样处理下，后续再继续优化。

**Comment by qingjiaowochengzd** [comment]
现在可以了
![4201f9dc-ba8a-4d41-9bea-7e6740fc1142](https://user-images.githubusercontent.com/30749028/37437643-417e5aa0-2829-11e8-85ab-6f8e0b2ad9da.png)
，昨天这么改也不行0.0,

**Comment by Sanbingo** [comment]
npm run dev后编译出错~
![image](https://user-images.githubusercontent.com/5332100/37484135-9c3b0d96-28c2-11e8-9965-a53bfcd25ca6.png)

**Comment by KuangPF** [comment]
你把 `package.json`里面`"mpvue-template-compiler": "^1.0.3"`,改为`"mpvue-template-compiler": "1.0.3"`,然后再安装一下包，这个问题我今天就优化下,就是由于这两个包的版本号不对造成的。

**Comment by KuangPF** [comment]
目前这个问题已经优化，`mpvue-template-compiler`的版本将与`mpvue`保持一致，为最新版。[commit](https://github.com/KuangPF/mpvue-weui/commit/2165c7044333c8000a590b9cc28b086d774ac1fb)
