### ISSUE TITLE
picker 确定按钮 在哪里改字体颜色？

### ISSUE THREAD

**Issue by PengMengShan** [KuangPF/mpvue-weui#44]
picker 确定按钮颜色在哪里修改？另外多级联动选择器在安卓手机上拉选择的时候 ，如果小程序定义了onPullDownRefresh ，安卓手机就一直拉onPullDownRefresh ，多级联动上拉没反应
![1539170156 1](https://user-images.githubusercontent.com/28291594/46733112-fec6dc80-ccc1-11e8-902a-b103904617ee.jpg)

**Comment by KuangPF** [comment]
这个目前 [picker](https://developers.weixin.qq.com/miniprogram/dev/component/picker.html) 组件没有提供改颜色的 api。
你说的下拉刷新的问题指的是：当组件滚动的时候会触发下拉刷新？

**Comment by PengMengShan** [comment]
对的  安卓手机会 上拉选择的时候 只触发小程序的下拉刷新

**Comment by PengMengShan** [comment]
就联动的组件会  其他单项的不会

**Comment by PengMengShan** [comment]
![1539219598 1](https://user-images.githubusercontent.com/28291594/46774258-1fc81580-cd34-11e8-8228-42f127776c0f.jpg)

**Comment by PengMengShan** [comment]
就上拉选择会触发小程序的下拉刷新，下拉选择不会

**Comment by KuangPF** [comment]
应该是 picker 组件的一个 bug ，详情见：
[自己写的弹窗上的 picker 滚动时，无法阻止picker页面里下拉刷新手势](https://developers.weixin.qq.com/community/develop/doc/000a6c069b0a78f760479932c51400?jumpto=comment&commentid=0006e856228a48f29c47d8739560)
