### ISSUE TITLE
有自定义的TabBar吗？小程序默认的限制太多了。

### ISSUE THREAD

**Issue by FisherMS** [KuangPF/mpvue-weui#45]
有自定义的TabBar吗？小程序默认的限制太多了。
比如：
1. 不能动态增减。
2. 从TabBar转到非TabBar页面后不能跳转了。
。。。。。。

**Comment by KuangPF** [comment]
暂时没有，下次迭代考虑加上。

**Comment by MarcWong** [comment]
可以考虑使用vant，我现在就是混着用的
