### ISSUE TITLE
关于mpvue新版本styles支持

### ISSUE THREAD

**Issue by qingjiaowochengzd** [KuangPF/mpvue-weui#5]
目前的1.0.1改不了styles属性，据说新版本修复了，我直接升1.0.5，报错mpvue-template-compiler版本不匹配,应该怎么升呢？
![6e317bbf4bc95ea21a793e7590e8f24](https://user-images.githubusercontent.com/30749028/37513289-a39fdbfc-293f-11e8-8444-d108a941c830.png)

**Comment by KuangPF** [comment]
你可以把`mpvue-template-compiler`和`mpvue`升级到同一个版本就可以了，目前都是 1.0.5，可在`package.json`里面修改。

**Comment by qingjiaowochengzd** [comment]
我下午都改成了1.0.5试了不行，奇怪现在克隆你的又是好的，你只改了这两个版本？

**Comment by KuangPF** [comment]
如果报的是你上述`mismatch`的错误，说明就是这两个包版本的问题，你可以在`node_modules`找到这两个包，然后看一下他们的版本是不是一样的，如果两个包的版本号是一样的却还是报错的话，我再看看是不是其他问题。

**Comment by qingjiaowochengzd** [comment]
谢谢，问题解决了
