### ISSUE TITLE
那个评分的组件不显示

### ISSUE THREAD

**Issue by 651584008** [KuangPF/mpvue-weui#53]
评分的那5颗星星没有显示出来

**Comment by KuangPF** [comment]
能否提供一下代码示例，我测了一下，可以正常显示，可以参考下[ rate demo](https://github.com/KuangPF/mpvue-weui/blob/master/src/pages/rate/index.vue)。

**Comment by 651584008** [comment]
看了demo 是因为样式没有写，谢谢你
