### ISSUE TITLE
Uploader图片上传放封装成一个子组件 然后子组件放在for循环内没有生效 点击没有反应

### ISSUE THREAD

**Issue by 651584008** [KuangPF/mpvue-weui#56]
Uploader图片上传用在for循环里面没有效果呢  
想做一个像淘宝评价页面的，然后因为设置mpvue的data里面的goods.imgs 这个二维数组页面没有同步刷新  然后考虑把上传抽出来做子组件 然后发现for循环里面没有生效

**Comment by KuangPF** [comment]
能否提供下代码呢，这样方便看下问题。
