### ISSUE TITLE
npm install  报错

### ISSUE THREAD

**Issue by ss7247** [KuangPF/mpvue-weui#59]
![Uploading K(Z`HX{AX@IL(3()JO[EN[5.png…]()

`

F:\wxcode\wxapp-vue>npm install
npm WARN deprecated bfj-node4@5.3.1: Switch to the `bfj` package for fixes and new features!
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.

> uglifyjs-webpack-plugin@0.4.6 postinstall F:\wxcode\wxapp-vue\node_modules\webpack\node_modules\uglifyjs-webpack-plugin
> node lib/post_install.js

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN vue-loader@13.7.3 requires a peer of vue-template-compiler@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN mpvue-weui@1.0.6 No repository field.
npm WARN mpvue-weui@1.0.6 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 987 packages from 673 contributors and audited 10658 packages in 70.871s
found 9 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
`

**Comment by ss7247** [comment]
![K(Z`HX{AX@IL(3()JO EN 5](https://user-images.githubusercontent.com/9480946/55816376-b9765100-5b24-11e9-88b7-78b0f81bccee.png)

**Comment by KuangPF** [comment]
这是警告吧，能够正常运行的。
