### ISSUE TITLE
mpvue 不能直接使用微信官方的那个weui?

### ISSUE THREAD

**Issue by softshower** [KuangPF/mpvue-weui#63]
mpvue 不能直接使用微信官方的那个weui?
所以才要用封装weui成mpvue-weui

**Comment by KuangPF** [comment]
在 mpvue 中，官方的 weui 有些可以直接使用，官方的 weui 是按照小程序的原生语法来写的，而 mpvue-weui 是按照 mpvue 的语法来写的。比如官方的 weui 组件中使用 setData 来改变一些数据，而在 mpvue 中通过将数据绑定在 vue 实例上，利用 getter/setter 让 data 的属性能够响应数据变化。
