### ISSUE TITLE
苹果样式可以，安卓样式不适配，编写样式有什么要求？

### ISSUE THREAD

**Issue by xujun820261729** [KuangPF/mpvue-weui#69]

**Comment by KuangPF** [comment]
编写样式没有要求，能否提供下具体的差异，例如截图之类的

**Comment by xujun820261729** [comment]
不好意思,是我编写代码有误！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"KuangPengfei"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月17日(星期二) 晚上11:51
收件人:&nbsp;"KuangPF/mpvue-weui"<mpvue-weui@noreply.github.com&gt;;
抄送:&nbsp;"云"<820261729@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [KuangPF/mpvue-weui] 苹果样式可以，安卓样式不适配，编写样式有什么要求？ (#69)




编写样式没有要求，能否提供下具体的差异，例如截图之类的
