### ISSUE TITLE
npm run dev 时 错误提示 error:  嵌套的 v-for 不能连续使用相同的 iterator: [ 'index', 'index' ]

### ISSUE THREAD

**Issue by liuhongyi0101** [KuangPF/mpvue-weui#7]
npm run dev 时 错误提示 error:  嵌套的 v-for 不能连续使用相同的 iterator: [ 'index', 'index' ]

但编译成功了

**Comment by liuhongyi0101** [comment]
"mpvue-loader": "^1.0.6",

**Comment by KuangPF** [comment]
在 `/index/index.vue` 中使用了 嵌套的 `v-for`，但使用了相同的索引，因此会有上述的错误提示，已修复。[commit](https://github.com/KuangPF/mpvue-weui/commit/6f6e9624d56193251e34ea78a9c8607129297fba)
