### ISSUE TITLE
关于多级联动选择ui优化

### ISSUE THREAD

**Issue by guigui730** [KuangPF/mpvue-weui#9]
用多级联动组件的时候，点击按钮打开选择框，背景层还是能滚动，跟微信自带的体验效果不太一样，能改进一下吗

**Comment by guigui730** [comment]
方便微信联系  截图看一下

**Comment by KuangPF** [comment]
已优化，你可以再试下。[commit](https://github.com/KuangPF/mpvue-weui/commit/c9ba59cb944539a720dc2a7fa3e819bbb09f8b7a)

**Comment by guigui730** [comment]
可以
